### ISSUE TITLE
Very thin font

### ISSUE THREAD

**Issue by nikic** [rustfoundation/foundation.rust-lang.org#31]
The font used for some of the subheadings like "A new approach to sustaining and growing a large, participatory, open source ecosystem" is extremely thin, making it hard to read.

Screenshot in case this is a platform specific issue (Firefox on Ubuntu 20.04):
![rust_foundation](https://user-images.githubusercontent.com/216080/107275024-84edbc00-6a51-11eb-9b18-18eb8509d33d.png)

**Comment by Aloso** [comment]
I agree, the font is next to unreadable. The text in the blog post is too thin as well, and _most_ of the text is way too small.

Also, on the orange background, the white text lacks contrast (especially when hovering a white link which then becomes orange).

**Comment by JoelMarcey** [comment]
I know this is an older issue, but it looks like the font as been thickened a bit from what I see now. I am going to close this issue, but if you think the font is still too thin, please re-open and we can see what we can do to move forward. Thanks!

**Comment by Aloso** [comment]
@JoelMarcey I don't see a difference to last year. Even if the font is (very slightly) thicker, it's still too thin to read comfortably.

**Comment by abibroom** [comment]
It's pretty easy to change the font weight since all we're doing is fetching from Google Fonts. At the moment we have:

`family=Lato:wght@100;300;900&family=Raleway:wght@200;400`

![200-400](https://user-images.githubusercontent.com/560001/163363311-02d3143f-0eb3-4b08-8a91-2880b35ad5f4.png)

Bumping [Raleway](https://fonts.google.com/specimen/Raleway) up to 300 and 500:

![300-500](https://user-images.githubusercontent.com/560001/163363373-9af1ba11-2bb8-40c8-b535-045e605f825c.png)

Or even further, to 400 and 600:

![400-600](https://user-images.githubusercontent.com/560001/163364012-38710872-6572-4fb8-9f2f-85e38f383eee.png)

**Comment by Aloso** [comment]
@abibroom Last time I offered my help here, @ashleygwilliams told me that they can't accept bigger community contributions, only small changes. Has this changed? Because I have quite a few ideas how the website can be improved. I'd like to change some fonts and font sizes to make the website more accessible, and I want to optimize the website for mobile devices.

**Comment by JoelMarcey** [comment]
@Aloso We are happy to consider and review pull requests. Of course, we may request changes or, for various reasons, not actually merge all of them, but we will definitely give them due.

As with most open source projects, pull requests are likely to get more quick attention than an issue where we then may have to implement something (unless it is critical, of course). That's just due to time constraints.
